# Generated by Django 2.2.15 on 2021-02-02 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20210201_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='click',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 8, 4, 25, 299868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='view',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 8, 4, 25, 300866, tzinfo=utc)),
        ),
    ]
